"""product_multiple_images

Revision ID: 20e58bae267a
Revises: ae74e273134e
Create Date: 2026-05-09 10:51:37.213303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20e58bae267a"
down_revision: Union[str, None] = "ae74e273134e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("image_urls", sa.ARRAY(sa.String()), nullable=True)
    )
    op.execute(
        "UPDATE products SET image_urls = ARRAY[image_url] WHERE image_url IS NOT NULL AND image_url != ''"
    )
    op.drop_column("products", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "image_url", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.execute(
        "UPDATE products SET image_url = image_urls[1] WHERE image_urls IS NOT NULL AND array_length(image_urls, 1) > 0"
    )
    op.drop_column("products", "image_urls")
    # ### end Alembic commands ###
