"""Cart Features

Revision ID: 423ea181cb0c
Revises: dce448404577
Create Date: 2026-05-07 03:05:42.775882

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "423ea181cb0c"
down_revision: str | None = "dce448404577"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_products_id", "products", ["id"], unique=False)

    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_order_items_id", "order_items", ["id"], unique=False)

    op.add_column("orders", sa.Column("amount_paid", sa.Float(), nullable=False))
    op.add_column("orders", sa.Column("total_amount", sa.Float(), nullable=False))
    op.drop_column("orders", "quantity")
    op.drop_column("orders", "cookies_type")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("cookies_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("orders", "total_amount")
    op.drop_column("orders", "amount_paid")

    op.drop_index("ix_order_items_id", table_name="order_items")

    op.drop_table("order_items")
    op.drop_index("ix_products_id", table_name="products")

    op.drop_table("products")
    # ### end Alembic commands ###
