"""add product_name snapshot to order_items

Revision ID: b9c5921e9b16
Revises: 423ea181cb0c
Create Date: 2026-05-07 05:53:46.911699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9c5921e9b16"
down_revision: Union[str, None] = "423ea181cb0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("product_name", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_column("product_name")

    # ### end Alembic commands ###
