"""add_available_dates

Revision ID: fc50303b4ff8
Revises: 20e58bae267a
Create Date: 2026-05-20 22:45:32.907260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc50303b4ff8'
down_revision: Union[str, None] = '20e58bae267a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('available_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_available_dates_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_available_dates_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('available_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_available_dates_id'))
        batch_op.drop_index(batch_op.f('ix_available_dates_date'))

    op.drop_table('available_dates')
    # ### end Alembic commands ###
