"""add_available_dates

Revision ID: fc50303b4ff8
Revises: 20e58bae267a
Create Date: 2026-05-20 22:45:32.907260

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc50303b4ff8"
down_revision: str | None = "20e58bae267a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "available_dates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_available_dates_date", "available_dates", ["date"], unique=True)
    op.create_index("ix_available_dates_id", "available_dates", ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_available_dates_id", table_name="available_dates")
    op.drop_index("ix_available_dates_date", table_name="available_dates")

    op.drop_table("available_dates")
    # ### end Alembic commands ###
